-- MySQL Script generated by MySQL Workbench
-- Mon Mar  3 10:54:44 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Perfiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Perfiles` (
  `ID_Perfil` INT NOT NULL,
  `Descrip` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Perfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `Cedula` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `email` VARCHAR(255) NOT NULL,
  `userCC` INT NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `ID_Perfil` INT NOT NULL,
  `Perfiles_ID_Perfil` INT NOT NULL,
  PRIMARY KEY (`Cedula`),
  UNIQUE INDEX `Cedula_UNIQUE` (`Cedula` ASC) VISIBLE,
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `userCC_UNIQUE` (`userCC` ASC) VISIBLE,
  INDEX `fk_user_Perfiles1_idx` (`Perfiles_ID_Perfil` ASC) VISIBLE,
  CONSTRAINT `fk_user_Perfiles1`
    FOREIGN KEY (`Perfiles_ID_Perfil`)
    REFERENCES `mydb`.`Perfiles` (`ID_Perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Permisos` (
  `ID_Permiso` INT NOT NULL,
  `Descrip` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Permiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Perfil_Primary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Perfil_Primary` (
  `ID_Perfil` INT NOT NULL,
  `ID_Permiso` INT NOT NULL,
  `Permisos_ID_Permiso` INT NOT NULL,
  `Perfiles_ID_Perfil` INT NOT NULL,
  PRIMARY KEY (`ID_Perfil`, `ID_Permiso`),
  INDEX `fk_Perfil_Primary_Permisos_idx` (`Permisos_ID_Permiso` ASC) VISIBLE,
  INDEX `fk_Perfil_Primary_Perfiles1_idx` (`Perfiles_ID_Perfil` ASC) VISIBLE,
  CONSTRAINT `fk_Perfil_Primary_Permisos`
    FOREIGN KEY (`Permisos_ID_Permiso`)
    REFERENCES `mydb`.`Permisos` (`ID_Permiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Perfil_Primary_Perfiles1`
    FOREIGN KEY (`Perfiles_ID_Perfil`)
    REFERENCES `mydb`.`Perfiles` (`ID_Perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
